{application,kubelet,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{kubelet_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[kubelet,kubelet_app,kubelet_sup,lib_application,
                        lib_kubelet,lib_kubelet_cmn,lib_workers,system_boot]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
